# Generated by Django 2.2.3 on 2019-11-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_basic_info',
            name='ID_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
