# Generated by Django 2.2.3 on 2019-11-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20191128_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach_basic_info',
            name='part',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
