# Generated by Django 2.2.3 on 2019-11-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20191128_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='part_info',
        ),
    ]
